blueprint:
  name: 💨 Управление вентиляцией по CO2 v13.5 (ФИНАЛ)
  description: >-
    Упрощенная автоматизация, которая управляет вентилятором по CO2,
    используя помощник `input_select` для отслеживания режима работы и
    обнаружения внешнего вмешательства. Добавлено уведомление, если CO2
    высокий, но вентилятор выключен в ручном режиме, с кнопкой для включения.
    **ФИНАЛЬНАЯ ВЕРСИЯ:** Исправлены ошибки 'too many values to unpack' и улучшено форматирование сообщения Telegram.
  domain: automation
  source_url: https://raw.githubusercontent.com/Eugen417/homeassistant-blueprints/refs/heads/main/gtc_co2_v13.1.yaml # Измените URL, если нужно

  input:
    co2_sensors:
      name: Датчики CO2
      description: Выберите один или несколько датчиков CO2.
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
          multiple: true
    target_fan:
      name: Целевой вентилятор
      description: >-
        Вентилятор, которым будет управлять автоматизация.
        **Обязательно используйте сущность с доменном `fan` (например, `fan.gtc_fan`),**
        который поддерживает установку скорости в процентах (`set_percentage`).
      default: fan.gtc_fan
      selector:
        entity:
          domain: fan
    automation_mode_select:
      name: Помощник Режима (Input Select)
      description: >-
        **Обязательный** `input_select` с опциями: **`RUNNING`** и **`WAITING`**.
      selector:
        entity:
          domain: input_select
    previous_co2_helper:
      name: Помощник для предыдущего CO2
      description: >-
        **Обязательный** `input_number` для хранения последнего значения CO2.
      selector:
        entity:
          domain: input_number
    low_co2_max:
      name: Нижний порог CO2 (макс, ppm)
      default: 600
      selector:
        number: { min: 400, max: 1000, step: 1, mode: box, unit_of_measurement: ppm }
    max_speed:
      name: Максимальная скорость вентилятора (%)
      default: 40
      selector:
        number: { min: 10, max: 100, step: 10, mode: slider, unit_of_measurement: '%' }
    co2_increase_threshold:
      name: Порог повышения CO2 для включения (ppm)
      default: 15
      selector:
        number: { min: 0, max: 100, step: 1, mode: box, unit_of_measurement: ppm }
    co2_change_threshold:
      name: Порог изменения CO2 для скорости (ppm)
      default: 15
      selector:
        number: { min: 0, max: 50, step: 1, mode: box, unit_of_measurement: ppm }
    start_speed:
      name: Минимальная/Стартовая Скорость (%)
      default: 0
      selector:
        number: { min: 0, max: 100, step: 10, mode: slider, unit_of_measurement: '%' }
    update_frequency:
      name: Частота проверки (minutes)
      default: "/5"
      selector:
        text:

    # ПОЛЯ ДЛЯ TELEGRAM
    telegram_notify_target:
      name: 💬 Telegram для уведомлений о блокировке
      description: Выберите сущности Telegram сервиса (notify.telegram_bot_...). Их ID будут извлечены для сервиса `telegram_bot.send_message`.
      default:
        entity_id: []
      selector:
        target:
          entity:
            - domain: notify

mode: single
trigger:
  - platform: time_pattern
    minutes: !input update_frequency
action:
  - variables:
      co2_sensors_list: !input co2_sensors
      target_fan_entity: !input target_fan
      low_co2_max_val: !input low_co2_max
      max_speed_val: !input max_speed
      co2_increase_threshold_val: !input co2_increase_threshold
      co2_change_threshold_val: !input co2_change_threshold
      start_speed_val: !input start_speed
      previous_co2_helper_entity_id: !input previous_co2_helper
      mode_select_entity_id: !input automation_mode_select
      telegram_notify_entities: !input telegram_notify_target

      current_mode: "{{ states(mode_select_entity_id) }}"
      is_fan_on: "{{ is_state(target_fan_entity, 'on') }}"

      min_fan_speed: >
        {% if start_speed_val | float == 0 %} 10 {% else %} {{ start_speed_val }} {% endif %}

      avg_co2: >
        {% set valid = co2_sensors_list | map('states') | map('float',0) | select('>',0) | list %}
        {% if valid | length > 0 %} {{ (valid | sum / valid | length) | round(1) }} {% else %} 0 {% endif %}

      current_speed: "{{ state_attr(target_fan_entity, 'percentage') | float(0) }}"
      previous_co2: "{{ states(previous_co2_helper_entity_id) | float(0) }}"

      # --- ИЗВЛЕЧЕНИЕ ID ЧАТОВ (как в Blueprint'е батарей) ---
      target_chat_ids: >-
        {% set selected = telegram_notify_entities.entity_id | default([]) %}
        {% set ids = selected | map('regex_replace', find='^.+_', replace='') | list %}
        {% set ns = namespace(targets=[]) %}
        {% for id_str in ids %}
          {% set clean_id = id_str | string | trim %}
          {% if clean_id | length > 10 and not clean_id.startswith('-') %}
            {% set ns.targets = ns.targets + ['-' ~ clean_id] %}
          {% else %}
            {% set ns.targets = ns.targets + [clean_id] %}
          {% endif %}
        {% endfor %}
        {{ ns.targets }}

  - choose:
      # --- ЛОГИКА 1: ВКЛЮЧЕНИЕ ВЕНТИЛЯТОРА ---
      - conditions:
          - condition: template
            value_template: "{{ not is_fan_on }}"
          - condition: template
            value_template: >
              {{ avg_co2 >= (low_co2_max_val | float + co2_increase_threshold_val | float) }}
          - condition: template
            value_template: "{{ current_mode == 'RUNNING' }}"
        sequence:
          - service: fan.turn_on
            target: { entity_id: "{{ target_fan_entity }}" }
          - delay: { seconds: 50 }
          - service: fan.set_percentage
            target: { entity_id: "{{ target_fan_entity }}" }
            data: { percentage: "{{ min_fan_speed }}" }
          - service: input_select.select_option
            target: { entity_id: "{{ mode_select_entity_id }}" }
            data: { option: WAITING }

      # --- ЛОГИКА 2: ВЕНТИЛЯТОР ВКЛЮЧЕН ---
      - conditions:
          - condition: template
            value_template: "{{ is_fan_on }}"
        sequence:
          - choose:
              # ВЫКЛЮЧЕНИЕ / МИН. СКОРОСТЬ
              - conditions:
                  - condition: template
                    value_template: |
                      {{ avg_co2 < low_co2_max_val | float }}
                sequence:
                  - if:
                      - condition: template
                        value_template: "{{ start_speed_val | float == 0 }}"
                    then:
                      - service: fan.set_percentage
                        target: { entity_id: "{{ target_fan_entity }}" }
                        data: { percentage: 10 }
                      - delay: { seconds: 5 }
                      - service: fan.turn_off
                        target: { entity_id: "{{ target_fan_entity }}" }
                      - service: input_select.select_option
                        target: { entity_id: "{{ mode_select_entity_id }}" }
                        data: { option: RUNNING }
                    else:
                      - service: fan.set_percentage
                        target: { entity_id: "{{ target_fan_entity }}" }
                        data: { percentage: "{{ start_speed_val }}" }
              # СНИЖЕНИЕ СКОРОСТИ
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (previous_co2 - avg_co2) >= co2_change_threshold_val | float }}
                sequence:
                  - variables: { new_speed: "{{ [current_speed - 10, min_fan_speed] | max }}" }
                  - service: fan.set_percentage
                    target: { entity_id: "{{ target_fan_entity }}" }
                    data: { percentage: "{{ new_speed }}" }
              # ПОВЫШЕНИЕ СКОРОСТИ
              - conditions:
                  - condition: template
                    value_template: |
                      {{ avg_co2 > previous_co2 }}
                sequence:
                  - variables: { new_speed: "{{ [current_speed + 10, max_speed_val] | min }}" }
                  - service: fan.set_percentage
                    target: { entity_id: "{{ target_fan_entity }}" }
                    data: { percentage: "{{ new_speed }}" }

  # --------------------------------------------------------------------------
  # --- ЛОГИКА 3: УВЕДОМЛЕНИЕ О БЛОКИРОВКЕ (Финальный рабочий блок) ---
  # --------------------------------------------------------------------------
  - choose:
      - conditions:
          - condition: template # Высокий CO2
            value_template: >
              {{ avg_co2 >= (low_co2_max_val | float + co2_increase_threshold_val | float) }}
          - condition: template # Вентилятор выключен
            value_template: "{{ not is_fan_on }}"
          - condition: template # Режим WAITING
            value_template: "{{ current_mode == 'WAITING' }}"
          - condition: template # Выбраны цели Telegram
            value_template: "{{ target_chat_ids | length > 0 }}"
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{ target_chat_ids }}"
              
              message: >
                {# 1. Определение Заголовка (Title) #}
                {%- set message_title = "💨 \*Внимание: Блокировка Вентустановки\*" %}
                
                {# 2. Определение Тела Сообщения (Message Body) #}
                {%- set raw_message_body = "Уровень CO2 (" ~ (avg_co2 | round(0)) ~ " ppm) выше установленного (порог: " ~ ((low_co2_max_val | float + co2_increase_threshold_val | float) | round(0)) ~ " ppm), но автоматизация не может запустить вентустановку, потому что она выключена вручную или другой автоматизацией. Текущий режим: WAITING." %}
                
                {# 3. Экранирование спецсимволов для MarkdownV2 (применяется только к телу!) #}
                {%- set escaped_body = raw_message_body | replace('&', '&amp;') | replace('~', '\~') | replace('`', '\`') | replace('>', '\>') | replace('#', '\#') | replace('+', '\+') | replace('-', '\-') | replace('=', '\=') | replace('|', '\|') | replace('{', '\{') | replace('}', '\}') | replace('.', '\.') | replace('!', '\!') | replace('*', '\*') | replace('_', '\_') | replace('[', '\[') | replace(']', '\]') | replace('(', '\(') | replace(')', '\)') | replace('%', '\%') %}
                
                {# 4. Объединение Заголовка и Тела #}
                {{ message_title ~ "\n\n" ~ escaped_body }}
              
              parse_mode: markdownv2
              
              # ИСПОЛЬЗУЕТСЯ ВАШ РАБОЧИЙ ФОРМАТ КНОПКИ
              inline_keyboard:
                - ВКЛЮЧИТЬ FAN:/turn_on_gtc_fan

  # ОБНОВЛЕНИЕ CO2
  - service: input_number.set_value
    data:
      entity_id: "{{ previous_co2_helper_entity_id }}"
      value: "{{ avg_co2 }}"
