blueprint:
  name: 💧 Уведомление о протечке v15.9 (Final Stable)
  description: >-
    Устранены проблемы с отправкой в телеграмм
  domain: automation
  source_url: https://raw.githubusercontent.com/Eugen417/homeassistant-blueprints/refs/heads/main/new_waterleackdeteckt_tts_push_notifi.yaml
  
  input:
    zone_1_name:
      name: Название Зоны 1
      default: 'Кухня'
      selector:
        text:
    leak_sensors_zone_1:
      name: Датчики Зоны 1
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
          multiple: true
      default: []
    water_shutoff_devices_zone_1:
      name: Краны Зоны 1
      selector:
        entity:
          domain: switch
          multiple: true
      default: []
    zone_2_name:
      name: Название Зоны 2
      default: 'Ванная'
      selector:
        text:
    leak_sensors_zone_2:
      name: Датчики Зоны 2
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
          multiple: true
      default: []
    water_shutoff_devices_zone_2:
      name: Краны Зоны 2
      selector:
        entity:
          domain: switch
          multiple: true
      default: []
    zone_3_name:
      name: Название Зоны 3
      default: 'Душевая'
      selector:
        text:
    leak_sensors_zone_3:
      name: Датчики Зоны 3
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
          multiple: true
      default: []
    water_shutoff_devices_zone_3:
      name: Краны Зоны 3
      selector:
        entity:
          domain: switch
          multiple: true
      default: []
    zone_4_name:
      name: Название Зоны 4
      default: 'Отопление'
      selector:
        text:
    leak_sensors_zone_4:
      name: Датчики Зоны 4
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
          multiple: true
      default: []
    water_shutoff_devices_zone_4:
      name: Краны Зоны 4
      selector:
        entity:
          domain: switch
          multiple: true
      default: []
    notify_device:
      name: Устройство для PUSH
      selector:
        device:
          integration: mobile_app
    telegram_notify_target:
      name: Telegram Notify Entity
      description: "Выберите сущности: notify.telegram_bot_..."
      default:
        entity_id: []
      selector:
        target:
          entity:
            - domain: notify
    notification_title:
      name: Заголовок
      default: '💧 ОБНАРУЖЕНА ПРОТЕЧКА!'
      selector:
        text:
    tts_media_players:
      name: Медиаплееры TTS
      selector:
        entity:
          domain: media_player
          multiple: true
      default: []
    tts_service:
      name: Сервис TTS
      default: tts.yandex_station_say
      selector:
        text:
    tts_volume:
      name: Громкость TTS
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
          mode: slider
      default: 0.7
    tts_delay_after_leak_message:
      name: Задержка проверки кранов (сек)
      description: Время между сообщением о протечке и проверкой, закрылись ли краны.
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider
      default: 11
    tts_delay_between_runs:
      name: Задержка между запусками
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider
      default: 5

variables:
  telegram_input: !input telegram_notify_target
  notif_title: !input notification_title
  # === ЛОГИКА ИЗ СКРИПТА BATTERY REPORT (Работает надежно) ===
  target_chat_ids: >
    {% set selected_entities_raw = telegram_input.entity_id | default([]) %} 
    {% set selected_entities = [selected_entities_raw] | flatten %} 
    {% set chat_id_strings = selected_entities | map('regex_replace', find='^.+_', replace='') | list %} 
    {% set ns = namespace(target_ids=[]) %} 
    {% for id_string in chat_id_strings %}
      {% set cleaned_id = id_string | string | trim %}
      {% if cleaned_id | length > 10 and not cleaned_id.startswith('-') %}
        {% set id_with_hyphen = '-' ~ cleaned_id %}
        {% set ns.target_ids = ns.target_ids + [id_with_hyphen] %}
      {% else %}
        {% set ns.target_ids = ns.target_ids + [cleaned_id] %}
      {% endif %}
    {% endfor %} 
    {{ ns.target_ids }}

trigger:
  - platform: state
    entity_id: !input 'leak_sensors_zone_1'
    to: 'on'
    alias: Протечка в первой зоне
  - platform: state
    entity_id: !input 'leak_sensors_zone_2'
    to: 'on'
    alias: Протечка во второй зоне
  - platform: state
    entity_id: !input 'leak_sensors_zone_3'
    to: 'on'
    alias: Протечка в третьей зоне
  - platform: state
    entity_id: !input 'leak_sensors_zone_4'
    to: 'on'
    alias: Протечка в четвертой зоне

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != 'unknown' }}"
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"

action:
  - choose:
      # ================= ЗОНА 1 =================
      - conditions: "{{ trigger.alias == 'Протечка в первой зоне' }}"
        sequence:
          - variables:
              zone: !input 'zone_1_name'
              valves: !input 'water_shutoff_devices_zone_1'
              # Очищаем имя датчика от английского текста
              sensor_name: "{{ trigger.to_state.attributes.friendly_name | default(trigger.to_state.name) | replace(' water leak', '') | replace(' Water leak detected', '') | replace(' Water Leak', '') }}"
          
          # 1. Закрываем краны
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ valves }}"
          
          # 2. Уведомление PUSH (Сразу) - ИСПРАВЛЕНО (Используем прямой вызов device)
          - if: "{{ notify_device is not none }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                title: "{{ notif_title }}"
                message: "⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}. Закрываю краны."

          # 3. Уведомление Telegram (Сразу)
          - choose:
              - conditions: "{{ target_chat_ids | length > 0 }}"
                sequence:
                  - service: telegram_bot.send_message
                    data:
                      target: '{{ target_chat_ids }}'
                      message: "<b>{{ notif_title }}</b>\n⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}.\n{% if valves | length > 0 %}🚰 Закрываю краны...{% endif %}"
                      parse_mode: html

          # 4. TTS (Первое сообщение)
          - service: media_player.volume_set
            target:
              entity_id: !input 'tts_media_players'
            data:
              volume_level: !input 'tts_volume'
          - service: !input 'tts_service'
            data:
              entity_id: !input 'tts_media_players'
              message: "Внимание! Протечка в зоне {{ zone }} от датчика {{ sensor_name }}. Закрываю краны."

          # 5. Задержка для закрытия кранов
          - delay:
              seconds: !input 'tts_delay_after_leak_message'

          # 6. Проверка результата и второе уведомление
          - choose:
              # СЦЕНАРИЙ А: Все краны закрыты (УСПЕХ)
              - conditions: "{{ valves | select('is_state', 'off') | list | length == valves | length }}"
                sequence:
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Я перекрыла все краны в зоне {{ zone }}."
                  - choose:
                      - conditions: "{{ target_chat_ids | length > 0 }}"
                        sequence:
                          - service: telegram_bot.send_message
                            data:
                              target: '{{ target_chat_ids }}'
                              message: "<b>✅ УСПЕШНО:</b> Все краны в зоне {{ zone }} перекрыты."
                              parse_mode: html

              # СЦЕНАРИЙ Б: Частичный успех или провал (если краны есть)
              - conditions: "{{ valves | length > 0 }}"
                sequence:
                  - variables:
                      failed: "{{ expand(valves) | selectattr('state','ne','off') | map(attribute='name') | list | join(', ') }}"
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Внимание! Не удалось закрыть некоторые краны в зоне {{ zone }}."
                  - choose:
                      - conditions: "{{ target_chat_ids | length > 0 }}"
                        sequence:
                          - service: telegram_bot.send_message
                            data:
                              target: '{{ target_chat_ids }}'
                              message: "<b>🚨 ОШИБКА:</b> Не закрыты краны в зоне {{ zone }}: {{ failed }}"
                              parse_mode: html

      # ================= ЗОНА 2 =================
      - conditions: "{{ trigger.alias == 'Протечка во второй зоне' }}"
        sequence:
          - variables:
              zone: !input 'zone_2_name'
              valves: !input 'water_shutoff_devices_zone_2'
              sensor_name: "{{ trigger.to_state.attributes.friendly_name | default(trigger.to_state.name) | replace(' water leak', '') | replace(' Water leak detected', '') | replace(' Water Leak', '') }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ valves }}"
          
          # PUSH FIX
          - if: "{{ notify_device is not none }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                title: "{{ notif_title }}"
                message: "⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."

          - choose:
              - conditions: "{{ target_chat_ids | length > 0 }}"
                sequence:
                  - service: telegram_bot.send_message
                    data:
                      target: '{{ target_chat_ids }}'
                      message: "<b>{{ notif_title }}</b>\n⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."
                      parse_mode: html
          - service: media_player.volume_set
            target:
              entity_id: !input 'tts_media_players'
            data:
              volume_level: !input 'tts_volume'
          - service: !input 'tts_service'
            data:
              entity_id: !input 'tts_media_players'
              message: "Протечка в зоне {{ zone }} от датчика {{ sensor_name }}. Закрываю краны."
          - delay:
              seconds: !input 'tts_delay_after_leak_message'
          - choose:
              - conditions: "{{ valves | select('is_state', 'off') | list | length == valves | length }}"
                sequence:
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Я перекрыла все краны в зоне {{ zone }}."
                  - choose:
                      - conditions: "{{ target_chat_ids | length > 0 }}"
                        sequence:
                          - service: telegram_bot.send_message
                            data:
                              target: '{{ target_chat_ids }}'
                              message: "<b>✅ УСПЕШНО:</b> Краны в зоне {{ zone }} закрыты."
                              parse_mode: html
              - conditions: "{{ valves | length > 0 }}"
                sequence:
                  - variables:
                      failed: "{{ expand(valves) | selectattr('state','ne','off') | map(attribute='name') | list | join(', ') }}"
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Внимание! Ошибка закрытия кранов в зоне {{ zone }}."
                  - choose:
                      - conditions: "{{ target_chat_ids | length > 0 }}"
                        sequence:
                          - service: telegram_bot.send_message
                            data:
                              target: '{{ target_chat_ids }}'
                              message: "<b>🚨 ОШИБКА:</b> Не закрыты: {{ failed }}"
                              parse_mode: html

      # ================= ЗОНА 3 =================
      - conditions: "{{ trigger.alias == 'Протечка в третьей зоне' }}"
        sequence:
          - variables:
              zone: !input 'zone_3_name'
              valves: !input 'water_shutoff_devices_zone_3'
              sensor_name: "{{ trigger.to_state.attributes.friendly_name | default(trigger.to_state.name) | replace(' water leak', '') | replace(' Water leak detected', '') | replace(' Water Leak', '') }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ valves }}"
          
          # PUSH FIX
          - if: "{{ notify_device is not none }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                title: "{{ notif_title }}"
                message: "⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."

          - choose:
              - conditions: "{{ target_chat_ids | length > 0 }}"
                sequence:
                  - service: telegram_bot.send_message
                    data:
                      target: '{{ target_chat_ids }}'
                      message: "<b>{{ notif_title }}</b>\n⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."
                      parse_mode: html
          - service: !input 'tts_service'
            data:
              entity_id: !input 'tts_media_players'
              message: "Обнаружена протечка в зоне {{ zone }}."
          - delay:
              seconds: !input 'tts_delay_after_leak_message'
          - choose:
              - conditions: "{{ valves | select('is_state', 'off') | list | length == valves | length }}"
                sequence:
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Краны в зоне {{ zone }} закрыты."
              - conditions: "{{ valves | length > 0 }}"
                sequence:
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Ошибка закрытия кранов в зоне {{ zone }}."

      # ================= ЗОНА 4 =================
      - conditions: "{{ trigger.alias == 'Протечка в четвертой зоне' }}"
        sequence:
          - variables:
              zone: !input 'zone_4_name'
              valves: !input 'water_shutoff_devices_zone_4'
              sensor_name: "{{ trigger.to_state.attributes.friendly_name | default(trigger.to_state.name) | replace(' water leak', '') | replace(' Water leak detected', '') | replace(' Water Leak', '') }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ valves }}"
          
          # PUSH FIX
          - if: "{{ notify_device is not none }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                title: "{{ notif_title }}"
                message: "⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."

          - choose:
              - conditions: "{{ target_chat_ids | length > 0 }}"
                sequence:
                  - service: telegram_bot.send_message
                    data:
                      target: '{{ target_chat_ids }}'
                      message: "<b>{{ notif_title }}</b>\n⚠️ Зона: {{ zone }}. Датчик: {{ sensor_name }}."
                      parse_mode: html
          - service: !input 'tts_service'
            data:
              entity_id: !input 'tts_media_players'
              message: "Внимание! Протечка в зоне {{ zone }}."
          - delay:
              seconds: !input 'tts_delay_after_leak_message'
          - choose:
              - conditions: "{{ valves | select('is_state', 'off') | list | length == valves | length }}"
                sequence:
                  - service: !input 'tts_service'
                    data:
                      entity_id: !input 'tts_media_players'
                      message: "Краны в зоне {{ zone }} перекрыты."

  - delay:
      seconds: !input 'tts_delay_between_runs'

mode: queued
max: 10
