id: homeassistant_person_tracker_telegram_v1.1

blueprint:
  name: 🏠 Отслеживание нескольких пользователей, уведомления в Telegram и определение их местоположения 📍
  description: |
    Отслеживание прихода/ухода выбранных пользователей (person.XXX) с генерацией
    интерактивной кнопки для запроса местоположения.
    
    ✅ Упрощенная настройка: ID чата теперь извлекается автоматически из имени сущности `notify.xxx`.
    
    ТРЕБОВАНИЕ: Для корректной работы кнопок и команд в Telegram необходимо убедиться,
    что ваш Telegram-бот настроен на режим `platform: polling` и поддерживает механизм
    callback-событий (см. пример конфигурации ниже).

    ---
    **ПРИМЕР КОНФИГУРАЦИИ TELEGRAM В configuration.yaml** 🤖
    (Обязательно замените placeholder-значения на свои!)
    ---
    
    telegram_bot:
      - platform: polling # ⚠️ Ключевой момент для приема команд/колбэков
        api_key: "ЗАМЕНИТЕ НА ВАШ_ТОКЕН_БОТА"
        parse_mode: html
        
        # ✅ ОБЯЗАТЕЛЬНО: Разрешенные ID чатов
        allowed_chat_ids:
          - -1234567890123 # ЗАМЕНИТЕ НА ВАШ ID группового чата (для уведомлений)
          - 987654321 # ЗАМЕНИТЕ НА ВАШ ID вашего личного аккаунта (для колбэков)
          
  source_url: https://raw.githubusercontent.com/Eugen417/homeassistant-blueprints/refs/heads/main/person_tracker_RU.yaml
          
  domain: automation
  input:
    # 1. СПИСОК ОТСЛЕЖИВАЕМЫХ PERSON
    tracked_persons:
      name: 📝𐦂𖨆𐀪𖠋Список отслеживаемых пользователей (person.XXX) 🗺️
      description: Выберите person-сущности для отслеживания.
      selector:
        entity:
          domain: person
          multiple: true
          
    # 2. СЕРВИС УВЕДОМЛЕНИЙ TELEGRAM
    telegram_notifications:
      name: ➤ Сервис уведомлений Telegram (notify.xxx) 🗺️
      description: Выберите сущность notify, созданную для Telegram-бота.
      selector:
        entity:
          domain: notify
          integration: telegram_bot

trigger:
  # Триггеры для ухода/прихода
  - platform: state
    entity_id: !input tracked_persons
    to: 'not_home'
  - platform: state
    entity_id: !input tracked_persons
    to: 'home'
  
  # Триггер для запроса местоположения (нажатие кнопки)
  - id: location_request
    platform: event
    event_type: telegram_callback

action:
  # 1. Определяем переменные-ID из input и АВТОМАТИЧЕСКИ ИЗВЛЕКАЕМ ID чата
  - variables:
      telegram_notifications_id: !input telegram_notifications
      tracked_persons_ids: !input tracked_persons

      # --- АВТОМАТИЧЕСКОЕ ИЗВЛЕЧЕНИЕ ID ЧАТА ИЗ notify.xxx ---
      notify_target_id: >-
        {% set entity_id = telegram_notifications_id | default('') %}
        {% set chat_id_part = entity_id | regex_replace(find='^.+_', replace='') | string | trim %}
        {% set final_id = chat_id_part %}
        {% if final_id | length > 10 and not final_id.startswith('-') %}
          {% set final_id = '-' ~ final_id %}
        {% endif %}
        {{ [final_id] }}
      
  - choose:
      # ВЫБОР 1: Уход из дома 🚶
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'state' and trigger.to_state.state == 'not_home' }}"
        sequence:
          - variables:
              triggered_person_id: "{{ trigger.entity_id }}"
              triggered_person_name: "{{ state_attr(trigger.entity_id, 'friendly_name') | default(trigger.entity_id.split('.')[1]) }}"
              button_command: "/где_{{ trigger.entity_id.split('.')[1] }}"
          
          - service: telegram_bot.send_message
            data:
              message: "{{ triggered_person_name }} вышел из квартиры 🚪"
              target: "{{ notify_target_id }}"
              parse_mode: plain_text
              inline_keyboard:
                - "Где сейчас {{ triggered_person_name }}? 🗺️:{{ button_command }}"
          
      # ВЫБОР 2: Приход домой 🏡
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'state' and trigger.to_state.state == 'home' }}"
        sequence:
          - variables:
              triggered_person_name: "{{ state_attr(trigger.entity_id, 'friendly_name') | default(trigger.entity_id.split('.')[1]) }}"
              
          - service: telegram_bot.send_message
            data:
              message: "{{ triggered_person_name }} вернулся домой! 👋"
              target: "{{ notify_target_id }}"
              parse_mode: plain_text
          
      # ВЫБОР 3: Запрос местоположения (Callback) 📍
      - conditions:
          - condition: trigger
            id: location_request
          - condition: template
            value_template: >
              {% set cmd_part = trigger.event.data.command.split('_')[1] | default('none') | lower %}
              {{ trigger.event.data.command.startswith('/где_') and 'person.' + cmd_part in tracked_persons_ids }}
        sequence:
          - variables:
              target_name_id: "{{ trigger.event.data.command.split('_')[1] }}"
              target_person_id: "person.{{ target_name_id }}" 
              target_person_name: "{{ state_attr(target_person_id, 'friendly_name') | default(target_person_id.split('.')[1]) }}"
              chat_id_response: "{{ trigger.event.data.chat_id | int }}"
              # Извлечение имени запросившего
              sender_name: >-
                {% set first_name = trigger.event.data.from_first | default('') %}
                {% set user_id = trigger.event.data.user_id | default('') %}
                
                {% if first_name | length > 0 %}
                  {{ first_name }}
                {% elif user_id | string | length > 0 %}
                  [ID: {{ user_id }}]
                {% else %}
                  Неизвестный пользователь
                {% endif %}
          
          # Отвечаем на callback (убираем надпись "Загрузка...")
          - service: telegram_bot.answer_callback_query
            data:
              callback_query_id: "{{ trigger.event.data.id }}"
              message: "Запрос от {{ sender_name }}. Ищу {{ target_person_name }}... ⏳"
              show_alert: false
          
          # Отправка статуса и карты
          - choose:
              # Если координаты ЕСТЬ
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr(target_person_id, 'latitude') is not none }}"
                sequence:
                  - variables:
                      # ФИКС: Используем чистую многострочную строку без HTML-тегов
                      status_message: |-
                        {% if is_state(target_person_id, 'home') %}
                          {{ target_person_name }} дома! 🏡
                        {% else %}
                          {{ target_person_name }} не дома! 🗺️
                        {% endif %}
                        Запрошено: {{ sender_name }}
                  
                  # 1. ОТПРАВЛЯЕМ ПЕРВОЕ СООБЩЕНИЕ (Статус + Имя)
                  - service: telegram_bot.send_message
                    data:
                      target: "{{ chat_id_response }}"
                      message: "{{ status_message }}"
                      parse_mode: plain_text # Используем plain_text
                      
                  # 2. ОТПРАВЛЯЕМ ВТОРОЕ СООБЩЕНИЕ (Карта)
                  - service: telegram_bot.send_location
                    data:
                      target: "{{ chat_id_response }}"
                      latitude: "{{ state_attr(target_person_id, 'latitude') }}"
                      longitude: "{{ state_attr(target_person_id, 'longitude') }}"
                  
              # Если координат НЕТ
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr(target_person_id, 'latitude') is none }}"
                sequence:
                  - service: telegram_bot.send_message
                    data:
                      target: "{{ chat_id_response }}"
                      # ФИКС: Используем чистую многострочную строку без HTML-тегов
                      message: |-
                        ⚠️ Местоположение {{ target_person_name }} сейчас неизвестно. ❓
                        Запрошено: {{ sender_name }}
                      parse_mode: plain_text # Используем plain_text

mode: single
