blueprint:
  name: Скриншот по движению + Telegram (Выбор сущности)
  description: >
    При обнаружении движения делает скриншот и отправляет его в выбранные чаты Telegram (парсинг из notify).
  domain: automation
  source_url: https://raw.githubusercontent.com/Eugen417/homeassistant-blueprints/refs/heads/main/photo_push_notifi_ru.yaml
  
  input:
    motion_sensor:
      name: Датчик движения
      selector:
        entity:
          domain:
            - binary_sensor
          device_class:
            - motion
            - presence
            - occupancymotion
          multiple: false
          reorder: false
    target_camera:
      name: Камера
      selector:
        entity:
          domain:
            - camera
          multiple: false
          reorder: false
    telegram_notify_target:
      name: "💬 Уведомления Telegram"
      description: Выберите сущности вашего сервиса Telegram (обычно называются notify.telegram_bot_...).
      default:
        entity_id: []
      selector:
        target:
          entity:
            - domain:
                - notify

mode: single

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'

action:
  - variables:
      camera_entity: !input target_camera
      telegram_notify_entities: !input telegram_notify_target
      
      # Используем статичный путь и имя файла (перезапись при каждом движении)
      path_snap: "/config/screenshot/vhod.jpg"
      
      camera_name: "{{ state_attr(camera_entity, 'friendly_name') or 'Камера' }}"
      target_chat_ids: >-
        {% set selected_entities_raw = telegram_notify_entities.entity_id | default([]) %}
        {% set selected_entities = [selected_entities_raw] | flatten %}
        {% set chat_id_strings = selected_entities | map('regex_replace', find='^.+_', replace='') | list %}
        {% set ns = namespace(target_ids=[]) %}
        {% for id_string in chat_id_strings %}
          {% set cleaned_id = id_string | string | trim %}
          {% if cleaned_id | length > 10 and not cleaned_id.startswith('-') %}
            {% set id_with_hyphen = '-' ~ cleaned_id %}
            {% set ns.target_ids = ns.target_ids + [id_with_hyphen] %}
          {% else %}
            {% set ns.target_ids = ns.target_ids + [cleaned_id] %}
          {% endif %}
        {% endfor %}
        {{ ns.target_ids }}

  - action: camera.snapshot
    target:
      entity_id: !input target_camera
    data:
      filename: "{{ path_snap }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ target_chat_ids | length > 0 }}"
        sequence:
          - action: telegram_bot.send_photo
            data:
              chat_id: "{{ target_chat_ids }}"
              file: "{{ path_snap }}"
              caption: "Тревога: <b>{{ camera_name }}</b>\nДвижение зафиксировано!"
              parse_mode: html
