blueprint:
  name: Обнаружение устройств Z2M (с защитой от циклов)
  description: >
    Проверяет датчики на доступность. Чтобы избежать бесконечных перезагрузок
    из-за одного сломанного датчика, добавлена проверка количества устройств.
  domain: automation
  source_url: https://raw.githubusercontent.com/Eugen417/homeassistant-blueprints/refs/heads/main/z2m_offline_detection.yaml
  input:
    check_interval:
      name: Интервал проверки (минуты)
      default: 30
      selector:
        number: { min: 1, max: 1440, unit_of_measurement: мин, mode: box }
    offline_threshold:
      name: Порог оффлайна (минуты)
      default: 60
      selector:
        number: { min: 1, max: 10000, unit_of_measurement: мин, mode: box }
    min_offline_count:
      name: Минимум устройств для действия
      description: Действие выполнится только если пропало столько устройств или больше. (Поставьте 1, если защита не нужна).
      default: 2
      selector:
        number: { min: 1, max: 50, mode: slider }
    exclude:
      name: Исключить устройства
      default: { entity_id: [] }
      selector:
        target: { entity: { domain: sensor } }
    actions:
      name: Действия
      description: Выполняется при превышении лимита пропавших устройств.
      selector:
        action: {}

variables:
  check_int: !input 'check_interval'
  threshold_min: !input 'offline_threshold'
  exclude_entities: !input 'exclude'
  min_count: !input 'min_offline_count'
  # Список пропавших устройств
  offline_list: >
    {% set result = namespace(sensors=[]) %}
    {% for state in states.sensor | rejectattr('attributes.device_class', 'undefined') | selectattr('attributes.device_class', '==', 'timestamp') %}
      {% if 'last_seen' in state.entity_id and not state.entity_id in exclude_entities.entity_id and (states(state.entity_id) == 'unavailable' or ((as_timestamp(now()) - as_timestamp(states(state.entity_id))) > ((threshold_min | int) * 60))) %}
        {% set result.sensors = result.sensors + [state.name] %}
      {% endif %}
    {% endfor %}
    {{ result.sensors }}
  # Считаем количество
  offline_count: "{{ offline_list | count }}"
  sensors: "{{ offline_list | join(', ') }}"

trigger:
  - platform: time_pattern
    minutes: "*"

condition:
  # Проверка интервала
  - condition: template
    value_template: "{{ (now().hour * 60 + now().minute) % (check_int | int) == 0 }}"
  # Проверка: устройств больше или равно лимиту
  - condition: template
    value_template: "{{ offline_count | int >= min_count | int }}"

action:
  - choose: []
    default: !input 'actions'

mode: single
